import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.LargestInducedTree
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.LocalGirthInducedTreeBound
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture13
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture141
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture17
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture315
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture322
import AmraLibrary.Combinatorics.SimpleGraph.GraphConjectures.WowiiConjecture58

/-!
Reusable AMRA Math library modules.

This file imports every registered reusable module.
-/
